databases:
  - name: nextgensummit2-db-free
    plan: free
    databaseName: nextgensummit2_db
    user: nextgensummit2

services:
  - type: web
    plan: free
    name: nextgensummit2-web
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nextgensummit2-db-free
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
